### PR TITLE
Add package with templates

### PR DESCRIPTION
**Pull request by Sod3n**
I think it will be pretty handy one, like one at framework itself. Not for all but simple systems that i use. Also change gitignore dont realy know if it will break smth.

### CODE REVIEW

**Comment by SH42913** [comment]
Works fine! Could you add instruction to README.md with new section `Templates for Unity`?
Also, you can add T2/T3 templates, but it's not necessary

**Comment by Sod3n** [comment]
Done

**Comment by SH42913** [comment]
@Sod3n, templates are fine, but you've changed formatting in Readme.MD and broke layout of `Templates for Rider` section. Also, there's typo in new section - vari**o**us. Could you commit only new section of Readme.MD?

**Comment by Sod3n** [comment]
Okay i think its fine now?

**Comment by SH42913** [comment]
Yeah, it's pretty good now :)
Thank you!🥇

**Pull request merged**
